mysql:
  image: mysql:5.6.26
  environment:
    - MYSQL_ROOT_PASSWORD=osm
    - MYSQL_DATABASE=osm
    - MYSQL_USER=osm
    - MYSQL_PASSWORD=osm

osm:
  image: thomass/openspeedmonitor
  links:
    - mysql:mysql
  ports:
    - "8080:8080"
